### ISSUE TITLE
Macro bypass

### ISSUE THREAD

**Issue by jcszymansk** [ciscoheat/immutable-hx#1]
ImmuTest.hx:

```
package;
class ImmuTest implements Immutable {
  public static function main() {
    var a = 1;
    Macro.assign(a, 2);
    trace(a);
  }
}
```

Macro.hx:

```
package;
import haxe.macro.Expr;
class Macro {
  public static macro function assign(v: Expr, ex: Expr) {
    return macro $v = $ex;
  }
}
```

and:

```
$ haxe -lib immutable --interp -main ImmuTest.hx
ImmuTest.hx:10: 2
```

**Comment by ciscoheat** [comment]
That's the same bailiwick as using `Reflect`, which can't really be avoided. I cannot save you from yourself! ;)

**Comment by jcszymansk** [comment]
Not really. Macros are quite popular, I could use a library macro inadvertently to reassign a supposedly read-only value, and reflection can't reassign locals. And it can be avoided by delaying the verification until after typed. :-)

**Comment by ciscoheat** [comment]
Yes, good point. I wish it was as simple as writing it in English though...

**Comment by ciscoheat** [comment]
Should be fixed now, with version 0.4.0. Think you can verify?

**Comment by jcszymansk** [comment]
Looks like it doesn't work still.

**Comment by ciscoheat** [comment]
Are you sure? I'm testing exactly that code, and it doesn't compile locally or on Travis. Try the latest version, 0.5.0.

**Comment by ciscoheat** [comment]
If you're using 3.3 however, the compiler may optimize away that assignment. Try something little more dynamic in that case. :)

**Comment by jcszymansk** [comment]
```
$ haxe -lib immutable:0.5.0 --interp -main ImmuTest.hx
ImmuTest.hx:10: 2
```

on 3.2.1. Maybe it's also an optimization?

**Comment by ciscoheat** [comment]
Yes, I'm looking at the generated code now, it's just replaced with `trace(2);`. It's a problem, I have to investigate. Thanks, I'll be back.

**Comment by ciscoheat** [comment]
Ok! 0.6.0 is available now. I didn't check all fields in [ClassType](http://api.haxe.org/haxe/macro/ClassType.html), it separates the constructor, statics and overrides when typed. But this problem also helped me disable the optimizations for 3.3: http://haxe.org/manual/cr-static-analyzer.html (local_dce to be precise)

So now should work both on 3.2 and 3.3! I hope you can confirm that for 3.2. Thanks for your help. :)

**Comment by jcszymansk** [comment]
It works on 3.2 now.

**Comment by ciscoheat** [comment]
Excellent, thanks.
